version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"  # Expose le backend sur le port 3000
    volumes:
      - ./backend/src:/app/src
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"  # Nginx servira le frontend sur le port 80 (exposé sur le port 8081 de l'hôte)
    depends_on:
      - backend
