version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8081:80"

  test-container:
    build:
      context: ./test-container
    depends_on:
      - backend
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/Library/Caches:/root/.cache/
    command: ["npm", "test"]

  trivy:
    image: aquasec/trivy:latest
    depends_on:
      - backend
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/Library/Caches:/root/.cache/
    entrypoint: ["sh", "-c", "trivy image ci-cd-pipeline_backend && trivy image ci-cd-pipeline_frontend"]

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
